import { useNavigate } from 'react-router-dom'
import { useState, useEffect } from 'react';
// import { getFunctions, httpsCallable } from 'firebase/functions'; // No longer needed here
// Firebase Imports for Firestore and Auth
import { getFirestore, collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { getAuth, onAuthStateChanged } from 'firebase/auth';
// Import Twemoji
import Twemoji from 'react-twemoji';
// Import the context hook
import { useTopics } from '../context/topics-context';

// Define the structure for topic suggestions (matching the backend)
interface TopicSuggestion {
    text: string;
    emojis: string; // String containing 1-2 emojis
}

// TODO: Initialize Firebase if not done globally
// import { initializeApp } from "firebase/app";
// const firebaseConfig = { /* Your config */ };
// initializeApp(firebaseConfig);

export function CreateStoryScreen() {
  const navigate = useNavigate();
  const firestore = getFirestore(); // Get Firestore instance
  const auth = getAuth(); // Get Auth instance

  // Use state from context
  const { topics, isLoadingTopics, topicsError, fetchTopics } = useTopics();
  
  // New State for selection and creation
  const [selectedTopic, setSelectedTopic] = useState<TopicSuggestion | null>(null);
  const [isCreatingStory, setIsCreatingStory] = useState<boolean>(false);
  const [createError, setCreateError] = useState<string | null>(null);
  const [userId, setUserId] = useState<string | null>(null);

  // Get current user ID
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (user) {
        setUserId(user.uid);
      } else {
        setUserId(null);
        // Handle not logged in state? Maybe redirect or show message.
        console.warn("User is not logged in.");
        // navigate('/login'); // Example redirect
      }
    });
    return () => unsubscribe(); // Cleanup subscription on unmount
  }, [auth]);

  // Handler for selecting a topic
  function handleSelectTopic(topic: TopicSuggestion) {
    setSelectedTopic(topic);
    setCreateError(null); // Clear previous creation errors on new selection
  }

  // Handler for creating the story
  async function handleCreateStory() {
    if (!selectedTopic || !userId) {
      setCreateError("Please select a topic and ensure you are logged in.");
      return;
    }

    setIsCreatingStory(true);
    setCreateError(null);

    try {
      console.log(`Creating story with topic: "${selectedTopic.text}" for user: ${userId}`);
      const storiesCollection = collection(firestore, 'stories');
      
      // Define the initial story document data
      // TODO: Add fields for selected length, characters etc. later
      const newStoryData = {
        userId: userId,
        topic: selectedTopic.text, // Store just the text
        title: null, // Will be generated by backend
        originalPrompt: null,
        characterIds: [], // Placeholder
        length: 'medium', // Placeholder default
        status: 'queued', // IMPORTANT: Set status to queued for the trigger
        errorMessage: null,
        plan: [],
        sections: [],
        createdAt: serverTimestamp(), // Use server timestamp
        updatedAt: serverTimestamp(), 
      };

      const docRef = await addDoc(storiesCollection, newStoryData);
      console.log("Story document created with ID: ", docRef.id);

      // Navigate to the new story page
      navigate(`/stories/${docRef.id}`);

    } catch (error: unknown) {
      console.error("Error creating story document:", error);
      let errorMessage = "Failed to create story document.";
      if (error instanceof Error) {
        errorMessage = error.message;
      } else if (typeof error === 'string') {
        errorMessage = error;
      }
      setCreateError(`Error: ${errorMessage}`);
      setIsCreatingStory(false); // Ensure loading state is reset on error
    } 
    // Don't set isCreatingStory to false on success, as we navigate away
  }


  return (
    // Reverted background, removed header, re-added absolute button and title
    <div className="flex flex-col items-center justify-center min-h-screen bg-blue-100 p-4 max-h-screen overflow-hidden relative">
      {/* Re-added absolute Back Button */}
      <button 
        className="absolute top-4 left-4 px-3 py-1.5 rounded-lg text-sm text-blue-700 bg-white bg-opacity-70 hover:bg-opacity-100 shadow-sm transition focus:outline-none focus:ring-2 focus:ring-blue-500"
        onClick={() => navigate(-1)} // Go back
      >
        Back
      </button>

      {/* Reverted title */}
      <h1 className="text-2xl sm:text-3xl font-bold mb-4 text-blue-800">Choose a Story Idea!</h1>
      
      {/* TODO: Add theme/preference selection */}

      {/* Reverted loading text */}
      {isLoadingTopics && (
        <div className="animate-pulse text-gray-600">Looking for Story Ideas...</div>
      )}

      {/* Reverted error message */}
      {topicsError && (
        <div className="text-red-600 bg-red-100 p-3 rounded mb-4">
          Oh dear, the story ideas got lost! 
          {/* Reverted Retry button text */}
          <button onClick={fetchTopics} className="ml-2 px-3 py-1.5 bg-red-500 text-white rounded text-sm font-medium focus:outline-none focus:ring-2 focus:ring-red-400 focus:ring-offset-1">
              Try Again
          </button>
        </div>
      )}

      {/* Topic Selection UI */}
      {!isLoadingTopics && !topicsError && topics.length > 0 && (
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 mb-6 w-full max-w-2xl">
          {topics.map((topic, index) => {
            const isSelected = selectedTopic?.text === topic.text && selectedTopic?.emojis === topic.emojis;
            return (
              <button 
                key={index} 
                onClick={() => handleSelectTopic(topic)}
                className={`flex flex-col items-center justify-center p-2 rounded-lg shadow-md transition duration-200 ease-in-out focus:outline-none h-22 sm:h-22 text-center ${
                  isSelected 
                    ? 'bg-green-500 text-white ring-2 ring-offset-2 ring-green-400' 
                    : 'bg-purple-500 text-white hover:bg-purple-600 focus:ring-2 focus:ring-purple-400 focus:ring-offset-2'
                }`}
              >
                <Twemoji options={{ className: 'twemoji' }} tag="div" className="mb-1 sm:mb-2 flex items-center justify-center gap-x-1 [&>img]:w-8 [&>img]:h-8 sm:[&>img]:w-8 sm:[&>img]:h-8">
                  {topic.emojis}
                </Twemoji>
                <span className="text-xs sm:text-sm font-medium">{topic.text}</span>
              </button>
            );
          })}
        </div>
      )}
      
      {/* Reverted No Topics Message */}
       {!isLoadingTopics && !topicsError && topics.length === 0 && (
           <p className="text-gray-600 mb-4">No ideas here yet. Try getting more?</p>
       )}

       {/* --- Buttons Row --- */}
       {!isLoadingTopics && (
         <div className="flex justify-center items-start gap-4 mb-4 w-full max-w-lg"> 
              {/* Refresh Button - Reverted text */}
              <button
                 onClick={fetchTopics} 
                 disabled={isLoadingTopics} 
                 className="px-5 py-2.5 sm:px-6 sm:py-3 bg-blue-500 text-white text-sm sm:text-base font-semibold rounded-lg shadow hover:bg-blue-600 disabled:opacity-50 flex-1 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-offset-2"
              >
                 {isLoadingTopics ? 'Searching...' : 'Get New Ideas!'}
              </button>
  
              {/* Create Story Button - Reverted text */}
              <button
                  onClick={handleCreateStory}
                  disabled={!selectedTopic || isCreatingStory || !userId}
                  className="px-5 py-2.5 sm:px-6 sm:py-3 bg-blue-600 text-white text-sm sm:text-base font-semibold rounded-lg shadow-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed flex-1 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
              >
                 {isCreatingStory ? 'Creating...' : 'Start Story!'}
              </button>
         </div>
       )}

       {/* --- Creation Feedback Area --- */}
       <div className="mt-2 w-full max-w-md flex flex-col items-center h-10"> 
          {/* Reverted Creation Error */}
           {createError && (
             <div className="text-red-600 bg-red-100 p-3 rounded mb-4 w-full text-center">Oops! Something went wrong creating the story.</div>
           )}
           {!userId && !isLoadingTopics && (
                <p className="text-sm text-red-600">Please log in to create a story.</p>
            )}
       </div>
    </div>
  )
} 