import { useNavigate } from 'react-router-dom'
import { useState, useEffect } from 'react';
import { getFunctions, httpsCallable } from 'firebase/functions';
// Firebase Imports for Firestore and Auth
import { getFirestore, collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { getAuth, onAuthStateChanged } from 'firebase/auth';
// Import Twemoji
import Twemoji from 'react-twemoji';

// Define the structure for topic suggestions (matching the backend)
interface TopicSuggestion {
    text: string;
    emojis: string; // String containing 1-2 emojis
}

// TODO: Initialize Firebase if not done globally
// import { initializeApp } from "firebase/app";
// const firebaseConfig = { /* Your config */ };
// initializeApp(firebaseConfig);

export function CreateStoryScreen() {
  const navigate = useNavigate();
  const functionsInstance = getFunctions(); // Get functions instance
  const firestore = getFirestore(); // Get Firestore instance
  const auth = getAuth(); // Get Auth instance

  // Update state to hold TopicSuggestion objects
  const [topics, setTopics] = useState<TopicSuggestion[]>([]); 
  const [isLoadingTopics, setIsLoadingTopics] = useState<boolean>(true);
  const [topicsError, setTopicsError] = useState<string | null>(null);
  
  // New State for selection and creation
  const [selectedTopic, setSelectedTopic] = useState<TopicSuggestion | null>(null);
  const [isCreatingStory, setIsCreatingStory] = useState<boolean>(false);
  const [createError, setCreateError] = useState<string | null>(null);
  const [userId, setUserId] = useState<string | null>(null);

  // Get current user ID
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (user) {
        setUserId(user.uid);
      } else {
        setUserId(null);
        // Handle not logged in state? Maybe redirect or show message.
        console.warn("User is not logged in.");
        // navigate('/login'); // Example redirect
      }
    });
    return () => unsubscribe(); // Cleanup subscription on unmount
  }, [auth]);

  // Function to fetch topics
  async function fetchTopics() {
    setIsLoadingTopics(true);
    setTopicsError(null);
    // Reset selection when fetching new topics
    setSelectedTopic(null); 
    console.log("Calling generateTopics function...");

    try {
      // Ensure user is logged in before fetching (generateTopics requires auth)
      if (!auth.currentUser) {
          throw new Error("User must be logged in to fetch topics.");
      }
      const generateTopics = httpsCallable(functionsInstance, 'generateTopics');
      const result = await generateTopics();
      const data = result.data as TopicSuggestion[]; 
      console.log("Received topics:", data);
      if (Array.isArray(data) && data.every(t => t && typeof t.text === 'string' && typeof t.emojis === 'string')) {
          setTopics(data);
      } else {
          console.error("Received invalid topic data structure:", data);
          throw new Error("Invalid data format received from server.")
      }
    } catch (error: unknown) {
      console.error("Error fetching topics:", error);
      let errorMessage = 'Unknown error';
      if (error instanceof Error) {
        errorMessage = error.message;
      } else if (typeof error === 'string') {
          errorMessage = error; // Handle string errors
      }
      setTopicsError(`Failed to load topics: ${errorMessage}`);
    } finally {
      setIsLoadingTopics(false);
    }
  }

  // Fetch topics when component mounts (and userId is available)
  useEffect(() => {
    // Only fetch if userId is known
    if (userId) {
      fetchTopics();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId]); // Re-fetch if userId changes (e.g., on login)

  // Handler for selecting a topic
  function handleSelectTopic(topic: TopicSuggestion) {
    setSelectedTopic(topic);
    setCreateError(null); // Clear previous creation errors on new selection
  }

  // Handler for creating the story
  async function handleCreateStory() {
    if (!selectedTopic || !userId) {
      setCreateError("Please select a topic and ensure you are logged in.");
      return;
    }

    setIsCreatingStory(true);
    setCreateError(null);

    try {
      console.log(`Creating story with topic: "${selectedTopic.text}" for user: ${userId}`);
      const storiesCollection = collection(firestore, 'stories');
      
      // Define the initial story document data
      // TODO: Add fields for selected length, characters etc. later
      const newStoryData = {
        userId: userId,
        topic: selectedTopic.text, // Store just the text, or the whole object? Let's store text for now.
        title: null, // Will be generated by backend
        originalPrompt: null,
        characterIds: [], // Placeholder
        length: 'medium', // Placeholder default
        status: 'queued', // IMPORTANT: Set status to queued for the trigger
        errorMessage: null,
        plan: [],
        sections: [],
        createdAt: serverTimestamp(), // Use server timestamp
        updatedAt: serverTimestamp(), 
      };

      const docRef = await addDoc(storiesCollection, newStoryData);
      console.log("Story document created with ID: ", docRef.id);

      // Navigate to the new story page
      navigate(`/stories/${docRef.id}`);

    } catch (error: unknown) {
      console.error("Error creating story document:", error);
      let errorMessage = "Failed to create story document.";
      if (error instanceof Error) {
        errorMessage = error.message;
      } else if (typeof error === 'string') {
        errorMessage = error;
      }
      setCreateError(`Error: ${errorMessage}`);
      setIsCreatingStory(false); // Ensure loading state is reset on error
    } 
    // Don't set isCreatingStory to false on success, as we navigate away
  }


  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-indigo-100 p-4">
      <h1 className="text-3xl font-bold mb-4 text-gray-800">Create a New Story</h1>
      {/* TODO: Add theme/preference selection */}

      {/* Loading State */}
      {isLoadingTopics && (
        <div className="animate-pulse text-gray-600">Loading topics...</div>
      )}

      {/* Error State (Topics) */}
      {topicsError && (
        <div className="text-red-600 bg-red-100 p-3 rounded mb-4">{topicsError}</div>
      )}

      {/* Topic Selection UI */}
      {!isLoadingTopics && !topicsError && topics.length > 0 && (
        <div className="grid grid-cols-3 gap-4 mb-6 w-full">
          {topics.map((topic, index) => {
            const isSelected = selectedTopic?.text === topic.text && selectedTopic?.emojis === topic.emojis;
            return (
              <button 
                key={index} 
                onClick={() => handleSelectTopic(topic)}
                className={`flex flex-col items-center justify-center p-2 rounded-lg shadow-md transition duration-200 ease-in-out focus:outline-none h-24 sm:h-22 text-center ${
                  isSelected 
                    ? 'bg-green-500 text-white ring-2 ring-offset-2 ring-green-400' 
                    : 'bg-purple-500 text-white hover:bg-purple-600 focus:ring-2 focus:ring-purple-400 focus:ring-opacity-75'
                }`}
              >
                <Twemoji options={{ className: 'twemoji' }} tag="div" className="mb-1 sm:mb-2 flex items-center justify-center gap-x-1 [&>img]:w-8 [&>img]:h-8 sm:[&>img]:w-10 sm:[&>img]:h-10">
                  {topic.emojis}
                </Twemoji>
                <span className="text-xs sm:text-sm font-medium">{topic.text}</span>
              </button>
            );
          })}
        </div>
      )}
      
      {/* No Topics Message */}
       {!isLoadingTopics && !topicsError && topics.length === 0 && (
           <p className="text-gray-600 mb-4">No topics loaded. Try refreshing.</p>
       )}

       {/* --- Buttons Row --- */}
       {!isLoadingTopics && (
         <div className="flex justify-center items-start gap-4 mb-4 w-full max-w-lg"> {/* New Flex container */} 
             {/* Refresh Button */} 
             <button
                 onClick={fetchTopics}
                 disabled={isLoadingTopics}
                 className="px-4 py-2 bg-blue-500 text-white rounded shadow hover:bg-blue-600 disabled:opacity-50 flex-1" // Use flex-1
             >
                 {isLoadingTopics ? 'Loading...' : 'Refresh Topics'}
             </button>
 
             {/* Create Story Button */}
             <button
                 onClick={handleCreateStory}
                 disabled={!selectedTopic || isCreatingStory || !userId}
                 className="px-6 py-2 bg-green-600 text-white rounded-lg shadow-md hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed flex-1" // Use flex-1, py-2 to match refresh
             >
                 {isCreatingStory ? 'Creating...' : 'Create Story'}
             </button>
         </div>
       )}

       {/* --- Creation Feedback Area --- */}
       <div className="mt-2 w-full max-w-md flex flex-col items-center h-10"> {/* Container for error/prompt, added fixed height */} 
          {/* Error State (Creation) */}
           {createError && (
             <div className="text-red-600 bg-red-100 p-3 rounded mb-4 w-full text-center">{createError}</div>
           )}
           {!userId && !isLoadingTopics && (
                <p className="text-sm text-red-600">Please log in to create a story.</p> // Removed margin top
            )}
       </div>


      {/* TODO: Add story length selection */} 

      <button 
        className="absolute top-4 left-4 px-4 py-2 bg-gray-300 rounded shadow hover:bg-gray-400 text-sm"
        onClick={() => navigate('/home')} // Go back home
      >
        Back to Home
      </button>
    </div>
  )
} 